on : push
jobs : 
      first-job:
          runs-on : ubuntu-latest
          steps :
                - uses : actions/checkout@v4
                - run : npx eslint
                - run : node index.js

